name: DominosCore
version: ${project.version}
main: dominos.core.dominoscore.DominosCore
api-version: 1.16
authors: [ Little_ ]
commands:
  tntfill:
    description: Fills local dispenser arrays
    usage: </command>
  tf:
    description: Fills local dispenser arrays
    usage: </command>
  magicsand:
    description: Gives a MagicSand generator
    usage: </command>
  ms:
    description: Gives a MagicSand generator
    usage: </command>
  magicconc:
    description: Gives a MagicConcrete generator
    usage: </command>
  mc:
    description: Gives a MagicConcrete generator
    usage: </command>
  getstacker:
    description: Gives a Stacker
    usage: </command>
  gs:
    description: Gives a Stacker
    usage: </command>
  discord:
    description: Discord invite
    usage: </command>
  ce:
    description: Clears Entities
    usage: </command>
  features:
    description: Gives you a list of features
    usage: </command>